### ISSUE TITLE
Summary / Rubric Score

### ISSUE THREAD

**Issue by karl-project-review** [ymopur/dvp-u6-netflix-data#1]
### Criteria 1: Pandas and CSV
* _Score Level:_ 4/4 (Exceeds Expectations)
* _Comment(s):_ You successfully imported the necessary libraries, loaded the CSV files into DataFrames, renamed the 'Adj Close' column, and calculated some maximums and minimums. Well done!
### Criteria 2: Implementation of visualizations in spec
* _Score Level:_ 3/4 (Meets Expectations)
* _Comment(s):_ The chart from step 6 showing the estimated vs actual earnings per share is not produced in the code nor included in the presentation. I would encourage you to go back and produce this chart, as being able to produce such a scatter plot is an important skill in data visualization.
### Criteria 3: Color
* _Score Level:_ 2/4 (Approaches Expectations)
* _Comment(s):_ While all of the charts are visually appealing, using blue for Netflix and red for the Dow Jones in the comparative line graphs is a confusing visual cue, since red is Netflix's go-to color. We need to always be cognizant of the associations colors are likely to have in a given context. 
### Criteria 4: Style
* _Score Level:_ 3/4 (Meets Expectations)
* _Comment(s):_ The majority of the titles and labels are clear. However, in the bar chart showing Netflix's revenue and earnings, there is no indication given that the y-axis labels represent billions of dollars. Be sure to always clearly indicate units, either in the axis labels or in the graph title.
### Criteria 5: Presentation and framing of visualization
* _Score Level:_ 3/4 (Meets Expectations)
* _Comment(s):_ Every chart is accompanied by a description and analysis, including evidence of calculating the minimums and maximums. However, be careful about saying earnings increase proportionately to revenue. Over the four quarters, earnings quadruple, while revenue increases by about 30%, which are very different rates of growth. 

### Overall Score: 15/20 (Meets Expectations)
Good job overall! You produced most of the charts and provided reasonable interpretations for them. To take your work to the next level, make sure to think through the associations people in a given context are likely to have to the colors used in your charts and to specify the units used. Also, I would encourage you to complete the step 6 scatter plot for extra practice. Again, well done!

**Comment by ymopur** [comment]
Thanks Karl. I appreciate your feedback and I have noted all your important feedback. I will ensure that I will keep these points in mind in the future
